package bll.eventos;

public enum AccionEvento {
        ENVIAR_PROPUESTA,
        APROBAR_PROPUESTA,
        RECHAZAR_PROPUESTA,
        AGREGAR_COMENTARIO,
        DEFINIR_CONDICIONES,
        CREAR_TITULO,
        TRANSFERIR_MARKETING,
        ACTUALIZAR_ESTADO_COMERCIALIZACION,
        CREAR_USUARIO,
        MODIFICAR_USUARIO,
        ELIMINAR_USUARIO,
        ASIGNAR_ROL
}
