CREATE TABLE IF NOT EXISTS usuarios (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  rol ENUM('ESCRITOR','EDITOR','ADMIN') NOT NULL DEFAULT 'ESCRITOR',
  biografia TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);